language: node_js

node_js:
  - "12"

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - development
    - /\d+\.\d+\.\d+/

install:
  - npm install -g codecov

script:
  - npm install
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # publish coverage info to coveralls

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_APIKEY
  on:
    repo: ibm-cloud-security/appid-clientsdk-js
    branch: master
