language: node_js

node_js:
  - "8"

notifications:
  email:
    on_success: always
    on_failure: always

branches:
  only:
    - master
    - development
    - /\d+\.\d+\.\d+/

install:
  - npm install -g codecov

script:
  - npm install
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js # publish coverage info to coveralls
